import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_name': 'Health AI Checkup',
      'nav_home': 'Home',
      'nav_dashboard': 'Dashboard',
      'nav_checkup': 'Checkup',
      'nav_catalog': 'Catalog',
      'nav_profile': 'Profile',
      'drawer_about': 'About',
      'drawer_privacy': 'Privacy',
      'greeting_ready': 'Ready for your next checkup?',
      'emergency': 'Emergency',
      'call_emergency': 'Call emergency',
      'health_score': 'Health score',
      'pull_refresh': 'Pull to refresh',
      'daily_highlights': 'Daily highlights',
      'dashboard_title': 'Health Dashboard',
      'ai_info_placeholder': 'AI description coming soon.',
      'device_checkup': 'Device Checkup',
      'ai_checkup': 'AI Checkup',
      'run_full_scan': 'RUN FULL HEALTH SCAN',
      'continue': 'Continue',
      'selected_symptoms': 'Selected symptoms',
      'reports': 'Reports',
      'view_report': 'View report',
      'catalog_search_hint': 'Search devices, vitals, tips',
      'filters': 'Filters',
      'add_compare': 'Add to compare',
      'compare': 'Compare',
      'empty_compare': 'Add at least two items to compare.',
      'go_to_catalog': 'Go to catalog',
      'settings': 'Settings',
      'dark_mode': 'Dark mode',
      'primary_color': 'Primary color',
      'language': 'Language',
      'notifications': 'Notifications',
      'profile_greeting': 'Hello',
      'bmi': 'BMI',
      'search': 'Search',
      'make_measurement': 'MAKE MEASUREMENT',
      'load_more': 'Load older days',
      'guest': 'Continue as guest',
      'login': 'Login',
      'signup': 'Sign up',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'password_strength': 'Password strength',
      'done': 'Done',
      'skip': 'Skip',
      'next': 'Next',
      'reports_status': 'Status',
      'global_search': 'Global search',
      'insights_lab': 'Insights lab',
      'journey_title': 'Streak momentum',
      'journey_completed': 'aligned',
      'mood_prompt': 'How are you feeling right now?',
      'mood_calm': 'Calm',
      'mood_focused': 'Focused',
      'mood_energized': 'Energized',
      'journey_timeline': 'Journey timeline',
      'insights_empty': 'No insights yet. Refresh to get new ideas.',
      'impact': 'Impact',
      'open_coach': 'Coach studio',
      'coach_room': 'Coach studio',
      'coach_empty': 'Coach plan coming soon.',
      'coach_intro': 'Micro goals to stabilize your vitals today',
      'coach_focus_body': 'Body',
      'coach_focus_mind': 'Mind',
      'coach_card_title': 'Guided rituals',
      'coach_card_subtitle': 'Stack short rituals with breathing, daylight and gratitude.',
      'start_micro_goal': 'Start micro goal',
      'view_all': 'View all',
      'home_insights_title': 'Smart insights',
      'home_insights_subtitle': 'Live coaching nudges',
      'journey_lab': 'Wellness journey',
      'mindfulness_room': 'Mindfulness studio',
      'sleep_lab': 'Sleep recovery',
      'journey_milestones': 'Journey milestones',
      'boosters': 'Boosters',
      'next_steps': 'Next steps',
      'home_wellness_title': 'Mind & recovery',
      'home_wellness_subtitle': 'Breath, sleep, focus',
      'breath_prompt': 'Breathe with the ring',
      'breathing_exercise': 'Breathing exercise',
      'guided_sessions': 'Guided sessions',
      'start_session': 'Start session',
      'inhale_label': 'Inhale',
      'exhale_label': 'Exhale',
      'sleep_quality': 'Sleep quality',
      'sleep_duration_hint': 'Avg nightly duration',
      'sleep_efficiency': 'Sleep efficiency',
      'deep_sleep': 'Deep sleep',
      'rem_sleep': 'REM sleep',
      'sleep_timeline': 'Sleep timeline',
      'night_notes': 'Night notes',
      'night_notes_hint': 'Log pre-bed rituals for better coaching.',
      'open_journey': 'Open journey',
      'minutes': 'min',
      'mindfulness_focus': 'Calm focus',
      'nutrition_lab': 'Nutrition lab',
      'macro_breakdown': 'Macro balance',
      'calories_today': 'Calories today',
      'snack_queue': 'Snack queue',
      'home_nutrition_title': 'Precision nutrition',
      'home_nutrition_subtitle': 'Meals tuned to today\'s vitals',
      'hydration_hub': 'Hydration studio',
      'hydration_timeline': 'Hydration timeline',
      'hydration_goal': 'Hydration goal',
      'log_glass': 'Log glass',
      'hydration_refill': 'Quick refill',
      'home_hydration_title': 'Hydration pulse',
      'home_hydration_subtitle': 'Micro sips every 90 min',
      'home_community_title': 'Community focus',
      'home_community_subtitle': 'Share boosts & accountability',
      'community_room': 'Community studio',
      'community_pulse': 'Community pulse',
      'community_moments': 'Mentor lineup',
      'community_join': 'Join live circle',
      'view_circle': 'View circle',
      'performance_lab': 'Performance lab',
      'home_performance_title': 'Mobility & strength',
      'home_performance_subtitle': 'Micro sessions and readiness',
      'readiness_score': 'Readiness',
      'movement_sessions': 'Movement sessions',
      'mobility_heat': 'Mobility heat',
      'recovery_room': 'Recovery studio',
      'home_recovery_title': 'Nervous system recovery',
      'home_recovery_subtitle': 'Reset + breathe deeper',
      'recovery_protocols': 'Recovery protocols',
      'soothing_moments': 'Soothing moments',
      'breath_sequences': 'Breath sequences',
      'nervous_system': 'Nervous system status',
      'mission_control': 'Mission control',
      'mission_readiness': 'Readiness orbit',
      'mission_pillars': 'Mission pillars',
      'mission_rituals': 'Prime rituals',
      'mission_timeline': 'Launch timeline',
      'home_mission_title': 'Mission control',
      'home_mission_subtitle': 'Align focus & rituals',
      'open_mission': 'Mission control',
      'companion_room': 'AI companion',
      'home_companion_title': 'Companion chat',
      'home_companion_subtitle': 'AI check-in for today',
      'ai_companion_prompts': 'Suggested prompts',
      'ai_companion_prompt_hint': 'Type a reflection or question',
      'ai_companion_typing': 'Assistant is typing…',
      'send': 'Send',
    },
    'ar': {
      'app_name': 'فحص الصحة بالذكاء الاصطناعي',
      'nav_home': 'الرئيسية',
      'nav_dashboard': 'لوحة الصحة',
      'nav_checkup': 'الفحص',
      'nav_catalog': 'الدليل',
      'nav_profile': 'الملف',
      'drawer_about': 'حول',
      'drawer_privacy': 'الخصوصية',
      'greeting_ready': 'هل أنت مستعد للفحص القادم؟',
      'emergency': 'طوارئ',
      'call_emergency': 'اتصال بالطوارئ',
      'health_score': 'درجة الصحة',
      'pull_refresh': 'اسحب للتحديث',
      'daily_highlights': 'أهم مهام اليوم',
      'dashboard_title': 'لوحة الصحة',
      'ai_info_placeholder': 'وصف الذكاء الاصطناعي قريباً.',
      'device_checkup': 'فحص الجهاز',
      'ai_checkup': 'فحص بالذكاء الاصطناعي',
      'run_full_scan': 'ابدأ الفحص الشامل',
      'continue': 'استمرار',
      'selected_symptoms': 'الأعراض المختارة',
      'reports': 'التقارير',
      'view_report': 'عرض التقرير',
      'catalog_search_hint': 'ابحث عن الأجهزة أو المؤشرات أو النصائح',
      'filters': 'المرشحات',
      'add_compare': 'أضف للمقارنة',
      'compare': 'المقارنة',
      'empty_compare': 'أضف عنصرين على الأقل للمقارنة',
      'go_to_catalog': 'اذهب إلى الدليل',
      'settings': 'الإعدادات',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الرئيسي',
      'language': 'اللغة',
      'notifications': 'الإشعارات',
      'profile_greeting': 'مرحباً',
      'bmi': 'مؤشر كتلة الجسم',
      'search': 'بحث',
      'make_measurement': 'ابدأ القياس',
      'load_more': 'تحميل أيام سابقة',
      'guest': 'الدخول كضيف',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'password_strength': 'قوة كلمة المرور',
      'done': 'تم',
      'skip': 'تخطي',
      'next': 'التالي',
      'reports_status': 'الحالة',
      'global_search': 'بحث شامل',
      'insights_lab': 'مختبر الرؤى',
      'journey_title': 'زخم العادات',
      'journey_completed': 'منجز',
      'mood_prompt': 'ما هو شعورك الآن؟',
      'mood_calm': 'هادئ',
      'mood_focused': 'مركز',
      'mood_energized': 'مفعم بالنشاط',
      'journey_timeline': 'مخطط الرحلة الصحية',
      'insights_empty': 'لا توجد رؤى حالياً، حدّث للحصول على مقترحات جديدة.',
      'impact': 'الأثر',
      'open_coach': 'غرفة التدريب',
      'coach_room': 'غرفة التدريب',
      'coach_empty': 'سيتم تجهيز خطة التدريب قريباً.',
      'coach_intro': 'أهداف مصغرة لتثبيت مؤشراتك اليوم',
      'coach_focus_body': 'الجسد',
      'coach_focus_mind': 'الذهن',
      'coach_card_title': 'طقوس موجهة',
      'coach_card_subtitle': 'اربط تنفساً وضوء النهار والامتنان في طقوس قصيرة.',
      'start_micro_goal': 'ابدأ الهدف المصغر',
      'view_all': 'عرض الكل',
      'home_insights_title': 'الرؤى الذكية',
      'home_insights_subtitle': 'تنبيهات تدريبية مباشرة',
      'journey_lab': 'رحلة العافية',
      'mindfulness_room': 'استوديو الهدوء',
      'sleep_lab': 'مختبر النوم',
      'journey_milestones': 'مراحل الرحلة',
      'boosters': 'محفزات',
      'next_steps': 'الخطوات التالية',
      'home_wellness_title': 'العقل والاستشفاء',
      'home_wellness_subtitle': 'تنفس، نوم، تركيز',
      'breath_prompt': 'تنفس مع الحلقة',
      'breathing_exercise': 'تمرين التنفس',
      'guided_sessions': 'جلسات موجهة',
      'start_session': 'ابدأ الجلسة',
      'inhale_label': 'شهيق',
      'exhale_label': 'زفير',
      'sleep_quality': 'جودة النوم',
      'sleep_duration_hint': 'متوسط مدة النوم',
      'sleep_efficiency': 'كفاءة النوم',
      'deep_sleep': 'نوم عميق',
      'rem_sleep': 'نوم ريم',
      'sleep_timeline': 'مخطط النوم',
      'night_notes': 'ملاحظات الليل',
      'night_notes_hint': 'سجل شعورك قبل النوم لمقترحات أدق.',
      'open_journey': 'افتح الرحلة',
      'minutes': 'دقائق',
      'mindfulness_focus': 'تركيز هادئ',
      'nutrition_lab': 'مختبر التغذية',
      'macro_breakdown': 'توزيع العناصر',
      'calories_today': 'سعرات اليوم',
      'snack_queue': 'وجبات خفيفة',
      'home_nutrition_title': 'التغذية الدقيقة',
      'home_nutrition_subtitle': 'وجبات مخصصة لمؤشراتك',
      'hydration_hub': 'استوديو الترطيب',
      'hydration_timeline': 'جدول الترطيب',
      'hydration_goal': 'هدف الترطيب',
      'log_glass': 'سجّل كوب',
      'hydration_refill': 'إعادة تعبئة سريعة',
      'home_hydration_title': 'نبض الترطيب',
      'home_hydration_subtitle': 'رشفة كل ٩٠ دقيقة',
      'home_community_title': 'مجتمع الدعم',
      'home_community_subtitle': 'شارك التحفيز والمساءلة',
      'community_room': 'استوديو المجتمع',
      'community_pulse': 'نبض المجتمع',
      'community_moments': 'سفراء المجتمع',
      'community_join': 'انضم للدائرة المباشرة',
      'view_circle': 'عرض الدائرة',
      'performance_lab': 'مختبر الأداء',
      'home_performance_title': 'الحركة والقوة',
      'home_performance_subtitle': 'جلسات دقيقة وقياس الجاهزية',
      'readiness_score': 'درجة الجاهزية',
      'movement_sessions': 'جلسات الحركة',
      'mobility_heat': 'خريطة المرونة',
      'recovery_room': 'استوديو الاستشفاء',
      'home_recovery_title': 'استشفاء الجهاز العصبي',
      'home_recovery_subtitle': 'أعد الضبط وتنفس بعمق',
      'recovery_protocols': 'بروتوكولات الاستشفاء',
      'soothing_moments': 'لحظات مهدئة',
      'breath_sequences': 'سلاسل التنفس',
      'nervous_system': 'حالة الجهاز العصبي',
      'mission_control': 'مركز المهام',
      'mission_readiness': 'مدار الجاهزية',
      'mission_pillars': 'محاور المهمة',
      'mission_rituals': 'الطقوس الأساسية',
      'mission_timeline': 'الخط الزمني للإطلاق',
      'home_mission_title': 'مركز المهام',
      'home_mission_subtitle': 'انسجام التركيز والطقوس',
      'open_mission': 'مركز المهام',
      'companion_room': 'المرافق الذكي',
      'home_companion_title': 'دردشة المرافق',
      'home_companion_subtitle': 'فحص اليوم بالذكاء الاصطناعي',
      'ai_companion_prompts': 'مقترحات للحديث',
      'ai_companion_prompt_hint': 'اكتب تأملًا أو سؤالًا',
      'ai_companion_typing': 'المرافق يكتب…',
      'send': 'إرسال',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
}

class _AppLocDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocDelegate old) => false;
}
